класс угловая мера
RomanKostin/Arc-length pull request #1
Opened 2024-03-21 18:03 UTC by RomanKostin

2024-03-27 13:34 UTC, MarinaPaley requested changes

2024-03-27 13:34 UTC, MarinaPaley commented on solver/Angle.cpp
> +	return (this->degrees != angle.degrees || this->minutes != angle.minutes || this->seconds != angle.seconds);
`return !(*this == angle);`

2024-03-27 13:34 UTC, MarinaPaley commented on solver/Angle.cpp
> +	}
```cpp
int degree = 0;
int minutes = 0;
double seconds = 0;
input >> degree >> minutes>> secondes;
temp Angle(degree, minutes, seconds);
std::swap(temp, angle);
return input;

2024-04-01 11:58 UTC, MarinaPaley requested changes

2024-04-01 11:58 UTC, MarinaPaley commented on solver/Angle.cpp
> +	if (min<0 || sec < -DBL_EPSILON || min>60 || sec - 60 > DBL_EPSILON)
`DBL_EPSILON` используйте при строгом равенстве или неравенстве. При меньше (больше) можно использовать `0`.
Введите `private static const factor = 60;`
И, кажется, что градусы надо брать по модулю 360...

2024-04-01 11:58 UTC, MarinaPaley commented on solver/Angle.cpp
> +	int negative = 1, temp_min;
`temp_min` не инициализирован...
его нужно ввести в строке 23, где и используется.
Полученные градусы нужно делить до тех пор, пока они не станут меньше 360.
Поэтому, нужно подумать о методах - установителях (сеттеры в других языках программирования). В них выделить логику заполнения полней.

2024-04-01 11:58 UTC, MarinaPaley commented on solver/Angle.cpp
> +	return(this->degrees == angle.degrees && this->minutes == angle.minutes && this->seconds == angle.seconds);
все ок, кроме сравнения на строгое равенство секунд. Только здесь `DBL_EPSILON` и нужно.

2024-04-01 11:58 UTC, MarinaPaley commented on solver/Angle.h
> +		bool operator == (const Angle& angle) const;
Тогда явно скажите, что деструктор и оператор и конструктор перемещения тоже по умолчанию.

2024-04-01 11:58 UTC, MarinaPaley commented on solver/Angle.h
> +		void swap(Angle& angle);
а эту функцию я бы отправила в `private`

2024-04-03 13:38 UTC, BalakinaEP approved these changes

2024-04-03 13:38 UTC, BalakinaEP commented on solver/Angle.cpp
> +	if (sec < DBL_EPSILON)
epsilon

2024-04-03 13:38 UTC, BalakinaEP commented on solver/Angle.cpp
> +	return(this->degrees == angle.degrees && this->minutes == angle.minutes && this->seconds - angle.seconds == DBL_EPSILON);
то же

2024-04-03 17:28 UTC, MarinaPaley requested changes
Не уверена в правильности расчета. Нужны тесты!

2024-04-03 17:28 UTC, MarinaPaley commented on solver/Angle.cpp
> +	this->degrees = (negative*(temp_min/factor)%360);
Вот не уверена я, что одного деления достаточно... Кажется, что нужен цикл. Пока не будет тестов, не скажу.
Ставьте пробелы для удобства читаемости.
```cpp
this->minutes = temp_min % factor;
```

2024-04-03 17:28 UTC, MarinaPaley commented on solver/Angle.cpp
> +	if (min<0 || sec < 0 || min > factor || sec > factor||fabs(degr)>360)
`std::abs(degr) > 360`, да и 360 почему константа?

2024-04-03 17:28 UTC, MarinaPaley commented on solver/Angle.cpp
> +	return(this->degrees == angle.degrees && this->minutes == angle.minutes && this->seconds - angle.seconds == DBL_EPSILON);
return this->degrees == angle.degrees && 
       this->minutes == angle.minutes && 
       std::abs(this->seconds - angle.seconds) <= DBL_EPSILON;

2024-04-10 16:28 UTC, MarinaPaley requested changes
Без тестов логику не проверю (из секунд в часы, минуты и секунды).

2024-04-10 16:28 UTC, MarinaPaley commented on solver/Angle.cpp
> +	if (min<0 || sec < 0 || min > factor || sec > factor||fabs(degr)>gradus_max)
`if (min<0 || sec < 0 || min > factor || sec > factor|| std::abs(degr) > gradus_max)`

[`fabs vs std::abs`](https://stackoverflow.com/questions/33738509/whats-the-difference-between-abs-and-fabs)

2024-04-10 16:28 UTC, MarinaPaley commented on solver/Angle.cpp
> +	if (sec < std::numeric_limits<double>::epsilon())
`if (sec < 0)`. только сравнение на строгое равенство или неравенство не имеет смысла

2024-04-10 16:28 UTC, MarinaPaley commented on solver/Angle.cpp
> +	return(this->degrees == angle.degrees && this->minutes == angle.minutes && fabs(this->seconds - angle.seconds) <= std::numeric_limits<double>::epsilon());
`std::abs`

2024-04-12 11:20 UTC, MarinaPaley approved these changes

2024-04-12 11:20 UTC, MarinaPaley commented on UnitTest1/UnitTest1.cpp
> +	TEST_CLASS(UnitTest1)
`UnitTest1` надо написать имя класса, к которому пишем тесты `AngleTests`

2024-04-12 11:32 UTC, merged